version: '3.4'

services:
  fc.codeflix.catalog.fb:
    container_name: catalogdb
    hostname: catalogdb
    image: mysql:5.7.16
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: c4t4l0g.@